### ISSUE TITLE
Ошибка "Object reference not set to an instance of an object." при получении постов со стены группы

### ISSUE THREAD

**Issue by unchase** [vknet/vk#1047]
**Описание ошибки**
При попытке получить список постов со стены публичной группы возникает ошибка **"Object reference not set to an instance of an object.".**

**Воспроизведение**
Для воспроизведения ошибки необходимо:
1. Создать .NET Core Console App
2. Добавить метод:

```csharp
public static async Task TestVkNet()
{
	try
	{
		using var api = new VkApi();
		api.Authorize(new ApiAuthParams
		{
			AccessToken = "f05e7e..." // используйте свой токен
		});
		var wallGetParams = new WallGetParams { Count = 10, Domain = "krddotnet" };
		var wall = await api.Wall.GetAsync(wallGetParams); // throws exception
	}
	catch (Exception e)
	{
            // здесь будет видна ошибка
	}
}
```

3. Вызвать метод `TestVkNet`
4. Увидите исключение с Message = **"Object reference not set to an instance of an object."**
StackTrace:

```
   at VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
   at VkNet.Model.PodcastInfo.FromJson(VkResponse response)
   at VkNet.Model.PodcastInfo.op_Implicit(VkResponse response)
   at VkNet.Model.Attachments.Podcast.FromJson(VkResponse response)
   at VkNet.Model.Attachments.Podcast.op_Implicit(VkResponse response)
   at VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   at VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
   at VkNet.Model.Attachments.Post.<>c.<FromJson>b__92_0(VkResponse x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](VkResponse response, Func`2 selector)
   at VkNet.Model.Attachments.Post.FromJson(VkResponse response)
   at VkNet.Model.Attachments.Post.op_Implicit(VkResponse response)
   at VkNet.Model.Attachments.Post.<>c.<FromJson>b__92_1(VkResponse x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](VkResponse response, Func`2 selector)
   at VkNet.Model.Attachments.Post.FromJson(VkResponse response)
   at VkNet.Model.Attachments.Post.op_Implicit(VkResponse response)
   at VkNet.Model.WallGetObject.<>c.<FromJson>b__16_0(VkResponse r)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](VkResponse response, Func`2 selector)
   at VkNet.Model.WallGetObject.FromJson(VkResponse response)
   at VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
   at VkNet.Categories.WallCategory.Get(WallGetParams params, Boolean skipAuthorization)
   at VkNet.Categories.WallCategory.<>c__DisplayClass0_0.<GetAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Ожидаемое поведение**
Исключение не должно возникать (ошибка должна обрабатываться внутри библиотеки).

**Скриншоты**

![vknet_error](https://user-images.githubusercontent.com/29679226/88490541-00e85100-cfa5-11ea-8cf5-8aa201e67cf4.png)

**Дополнительная информация**
Загнал аналогичный метод в тестовый проект библиотеки, получил то же исключение здесь (`VkNet\Utils\Vk.Response.cs` 169 строка):

![vknet_error2](https://user-images.githubusercontent.com/29679226/88490589-4d339100-cfa5-11ea-99f1-e950a543901f.png)

**Comment by equuskk** [comment]
Не воспроизводится
Код:

```csharp
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;
using VkNet;
using VkNet.Abstractions;
using VkNet.Infrastructure;
using VkNet.Model;
using VkNet.Model.RequestParams;

namespace DemoDemoDemo
{
	internal class Program
	{
		private static IVkApi _vkApi;

		private static async Task Main(string[] args)
		{
			InitVkApi();

			var wallGetParams = new WallGetParams
			{
				Count = 10,
				Domain = "krddotnet"
			};

			var wall = await _vkApi.Wall.GetAsync(wallGetParams); // throws exception
		}

		private static void InitVkApi()
		{
			Log.Logger = new LoggerConfiguration()
				.MinimumLevel
				.Debug()
				.WriteTo
				.Console()
				.CreateLogger();

			// Контейнер для инверсии зависимостей
			var services = new ServiceCollection();

			// Регистрация логгера
			services.AddLogging(builder =>
			{
				builder.ClearProviders();
				builder.SetMinimumLevel(LogLevel.Trace);
				builder.AddSerilog(dispose: true);
			});

			_vkApi.Authorize(new ApiAuthParams
			{
				AccessToken = "****"
			});
		}
	}
}
```

Логи:
```
[15:01:44 DBG] VkApi Initialization successfully
[15:01:44 DBG] Авторизация через токен
[15:01:44 DBG] Авторизация прошла успешно
[15:01:44 DBG] Вызов метода wall.get, с параметрами domain=krddotnet,offset=0,count=10,extended=0,v=5.120
[15:01:44 DBG] POST request: https://api.vk.com/method/wall.get
{
  "domain": "krddotnet",
  "offset": "0",
  "count": "10",
  "extended": "0",
  "v": "5.120",
  "access_token": "***HIDDEN***"
}
[15:01:45 DBG] Response:
{
  "response": {
    "count": 48,
    "items": [...],
    "next_from": "10"
  }
}
```

**Comment by unchase** [comment]
@equuskk 
Проверял именно в .NET Core Console App?

Я только что воспроизвел в чистом проекте:

![exception](https://user-images.githubusercontent.com/29679226/88960156-c3890980-d2ab-11ea-866e-843d862ccd46.png)

```csharp
class Program
{
	static void Main(string[] args)
	{
		InitVkApi();

		var wallGetParams = new WallGetParams
		{
			Count = 10,
			Domain = "krddotnet"
		};

		var wall = _vkApi.Wall.GetAsync(wallGetParams).GetAwaiter().GetResult(); // throws exception
	}

	private static IVkApi _vkApi;

	private static void InitVkApi()
	{
		_vkApi.Authorize(new ApiAuthParams
		{
			AccessToken = "****"
		});
	}
}
```

И может проблема быть связана с тем, что я использую [сервисный ключ доступа](https://vk.com/dev/service_token)?

**Comment by equuskk** [comment]
@unchase Да, консольное .NET Core, но я вызывал с токеном пользователя

Проверил с сервисным токеном - падает из-за того, что в возвращаемом JSON отсутствует поле Position. Если его закомментировать тут, то код выполняется корректно.
```
public static PodcastInfo FromJson(VkResponse response)
{
	return new PodcastInfo
	{
		Cover = response["cover"],
		Plays = response["plays"],
		IsFavorite = response["is_favorite"],
		Description = response["description"],
		Position = response["position"]
	};
}
```

**Comment by unchase** [comment]
> @unchase Да, консольное .NET Core, но я вызывал с токеном пользователя
> 
> Проверил с сервисным токеном - падает из-за того, что в возвращаемом JSON отсутствует поле Position. Если его закомментировать тут, то код выполняется корректно.
> 
> ```
> public static PodcastInfo FromJson(VkResponse response)
> {
> 	return new PodcastInfo
> 	{
> 		Cover = response["cover"],
> 		Plays = response["plays"],
> 		IsFavorite = response["is_favorite"],
> 		Description = response["description"],
> 		Position = response["position"]
> 	};
> }
> ```

Ну я же не закомментирую в подключенном nuget-пакете. Надо исправить в самой библиотеке, чтобы корректно обрабатывало этот случай.
