### ISSUE TITLE
The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.

### ISSUE THREAD

**Issue by rhiskey** [vknet/vk#1164]
1. Target для .NET используемый в проекте: 
  - [X] другое. Указать строкой ниже.
  - .NET Core 3.1
  
2. Класс и метод в котором возникла проблема: VkNet.VkApi.Authorize

3. Пример кода для воспроизведения проблемы:

```csharp
     api.Authorize(new ApiAuthParams() 
        {                                   
           Login = "79991234567",
           Password = "a*B42||E]0Pl^+11",
           ApplicationId = 2685278,
           Settings = Settings.All 
        }); 
```

4. Stacktrace.

```
Error Message: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
Stack Trace:    at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   at System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
   at VkNet.Utils.RestClient.CallAsync(Func`1 method)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.Forms.AbstractAuthorizationForm.ExecuteAsync(Uri url, IApiAuthParams authParams)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.NextStepAsync(AuthorizationFormResult formResult)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.Authorize(ApiAuthParams params)

```

5. Если в примере не указаны конкретные значения параметров запроса укажите их здесь:            
           Login = "телефон",
           Password = "a*B42||E]0Pl^+11", -примерный набор символов
           ApplicationId = 2685278,

**Comment by fixer-m** [comment]
У меня такая же ошибка. 
Нашел временное решение: `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)` (до авторизации VkApi)

**VkApi version:** 1.63.0-621 (pre-release)
**Runtime:** .NET 5.0
**Platform:** Windows 10
**Application type:** Console
**Exception:** System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.
**Inner Exception:** System.ArgumentException: 'windows-1251' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
**Stack Trace:** 
```
   at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   at System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
   at VkNet.Utils.RestClient.CallAsync(Func`1 method)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.AuthorizationFormHtmlParser.GetFormAsync(Uri url)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.Forms.AbstractAuthorizationForm.ExecuteAsync(Uri url, IApiAuthParams authParams)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
```

**Comment by rhiskey** [comment]
> Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)

Добавил перед методом Authorize() , теперь другая ошибка при авторизации:
```
Error Message: Failed to determine page type from url: https://oauth.vk.com/auth_redirect?app_id=2685278&authorize_url=https%253A%252F%252Foauth.vk.com%252Fblank.html%2523access_token%111111expires_in%111user_id%123%2526email%253Dtest%2540mail.ru&redirect_hash=213123
Stack Trace:    at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlowVkAuthorization.GetPageType(Uri url)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.NextStepAsync(AuthorizationFormResult formResult)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.NextStepAsync(AuthorizationFormResult formResult)
   at VkNet.Infrastructure.Authorization.ImplicitFlow.ImplicitFlow.AuthorizeAsync()
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
```

**Comment by fixer-m** [comment]
@rhiskey, [Пофиксили в бетке](https://github.com/vknet/vk/pull/1166). Однако, бетка зачем-то требует .NET 5.0, см. последний коммент.
