### ISSUE TITLE
Не работает авторизация (.Net Core 2.0)

### ISSUE THREAD

**Issue by redmanmale** [vknet/vk#489]
Используется двухфакторная авторизация.

```csharp
var apiAuthParams = new ApiAuthParams
{
    ApplicationId = appId,
    Login = login,
    Password = password,
    Settings = Settings.Audio,
    TwoFactorAuthorization = TwoFactorAuthorization
};

_engineVk = new VkApi();
_engineVk.Authorize(apiAuthParams); // <-- падает здесь


private static string TwoFactorAuthorization()
{
    Console.Write("Please enter security code:");
    return Console.ReadLine();
}
```

Исключение:
```
Unhandled Exception: System.InvalidOperationException: This operation is not sup
ported for a relative URI.
   at System.Uri.get_AbsoluteUri()
   at VkNet.Utils.WebCall.MakeRequest(HttpResponseMessage response, Uri uri, IWe
bProxy webProxy)
   at VkNet.Utils.WebCall.Post(WebForm form, IWebProxy webProxy)
   at VkNet.Utils.Browser.Authorize(UInt64 appId, String email, String password,
 Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   at VkNet.VkApi.Authorize(UInt64 appId, String emailOrPhone, String password,
Settings settings, Func`1 code, Nullable`1 captchaSid, String captchaKey)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(UInt64 appId, String emailOrPhone, St
ring password, Settings settings, Func`1 code, Nullable`1 captchaSid, String cap
tchaKey)
   at VkNet.VkApi.Authorize(ApiAuthParams params)
   at Redmanmale.VkUtils.VkHelper..ctor(String login, String password, UInt64 ap
pId, Nullable`1 userId) in ...
```

VkNet v.1.29.2, .NET Core 2.0, Win 8.1 x64

**Comment by redmanmale** [comment]
Воспроизводится не всегда.

**Comment by SanteR1** [comment]
Сегодня столкнулся с такой же проблемой. Работала программа исправно, сегодня утром стала выдавать ошибку
`{"Invalid authorization with ****login** - ****password***"}`
Проверил авторизацию через сайт, все в порядке, сменил пароль, ошибка повторяется. 
Делаю тест через другой логин/пароль - все работает, возвращаюсь к основному, ошибка.
Последняя сборка с GitHub, .NET Framework 4.5

**Comment by inyutin-maxim** [comment]
Дублирует https://github.com/vknet/vk/issues/494
