### ISSUE TITLE
The type 'pretty_cards' of attachment is not defined

### ISSUE THREAD

**Issue by infinitu1327** [vknet/vk#534]
Версия: 1.30.2

Пытаюсь получить список фотографий из сообщений беседы. Делаю это через Messages.GetHistory. Почему не через GetHistoryAttachments? Потому что GetHistoryAttachments по какой-то причине возвращает не все вложения беседы. При получении сообщений вылетает следующее исключение: The type 'pretty_cards' of attachment is not defined. 

```   at VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.Post.FromJson(VkResponse response)
   at VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.Message.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.MessagesGetObject.FromJson(VkResponse response)
```

Ниже представлен тестовый метод, в котором я пока пытаюсь сосчитать общее количество фотографий, прикреплённых к сообщениям беседы.

- Пример кода для воспроизведения проблемы:

```csharp
        private static List<Uri> GetPhotosLinksForDialog(int dialogId)
        {
            var offset = 0;
            uint totalCount = 0;
            var count = 0;

            do
            {
                var messages = Vk.Messages.GetHistory(new MessagesGetHistoryParams
                {
                    Count = 200,
                    Offset = offset,
                    PeerId = 2000000000 + dialogId
                });

                offset += messages.Messages.Count;
                totalCount = messages.TotalCount;

                count += messages.Messages.Sum(m => m.Attachments.Count(a => a.Type == typeof(Photo)));
            } while (offset <= totalCount);

            return new List<Uri>();
        }
```

**Comment by inyutin-maxim** [comment]
@infinitu1327 для того чтобы поправить необходимо предоставить json ответ от vk чтобы описать объект pretty_cards, в документации не нашел объекта

**Comment by infinitu1327** [comment]
https://pastebin.com/xTz4LB6x
https://pastebin.com/jq2FnRM0
Вот пару примеров JSON'ов

**Comment by inyutin-maxim** [comment]
@infinitu1327 Спасибо, по возможности добавим

**Comment by inyutin-maxim** [comment]
@infinitu1327 Добавлено к следующему релизу
