### ISSUE TITLE
Ошибка при авторизации пользователя Form element not found

### ISSUE THREAD

**Issue by dvygolov** [vknet/vk#547]
Использую библиотеку в Azure Function. При авторизации выдаётся та же ошибка, что и у камрада в #452 : Form Element Not Found. Двухфакторка в аккаунте, который используется в работе, отключена. Код совершенно обычный:
```

            var vk = new VkApi();
            var authParams = new ApiAuthParams()
            {
                ApplicationId = appId,
                Login = "xxx@gmail.com",
                Password = "xxxx",
                Settings =
                    Settings.Documents | Settings.Friends | Settings.Groups | Settings.Messages |
                    Settings.Notes | Settings.Offline | Settings.Pages | Settings.Photos |
                    Settings.Video | Settings.Wall
            };
            vk.Authorize(authParams);

```
Прикладываю скрины с Azure Portal. 
![image](https://user-images.githubusercontent.com/9249545/35223519-166892f6-ff9b-11e7-9636-c30820ec4414.png)
![image](https://user-images.githubusercontent.com/9249545/35223546-2d3fcf4e-ff9b-11e7-883d-c351c14b36e2.png)

**Comment by inyutin-maxim** [comment]
@dvygolov Попробуйте использовать альфу из [https://www.myget.org/F/vknet-alpha/api/v3/index.json](https://www.myget.org/F/vknet-alpha/api/v3/index.json). Отпишитесь о результатах, спасибо

**Comment by dvygolov** [comment]
Попробовал, результат тот же:
Starting...
```
Exception while executing function: AddFriendsFunction
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: AddFriendsFunction ---> VkNet.Exception.VkApiException : Form element not found.
   at VkNet.Utils.WebForm.GetFormNode()
   at VkNet.Utils.WebForm.ParseInputs()
   at VkNet.Utils.WebForm..ctor(WebCallResult result)
   at VkNet.Utils.Browser.EndAuthorize(WebCallResult result,IWebProxy webProxy)
   at VkNet.Utils.Browser.Authorize(IApiAuthParams authParams)
   at VkNet.VkApi.BaseAuthorize(IApiAuthParams authParams)
   at VkNet.VkApi.AuthorizeWithAntiCaptcha(IApiAuthParams authParams)
   at VkNet.VkApi.Authorize(IApiAuthParams params)
   at AddVkFriends.AddFriendsFunction.Run(TimerInfo myTimer,TraceWriter log) at D:\home\site\repository\AddVkFriends\AddFriendsFunction.cs : 27
   at lambda_method(Closure ,AddFriendsFunction ,Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

**Comment by inyutin-maxim** [comment]
@dvygolov Можете собрать fiddler'ом логи авторизации? видимо в какой то момент вам приходит не верная страница

**Comment by dvygolov** [comment]
К сожалению, не могу этого сделать. Взял исходники попробую записать в лог адрес страницы и её содержимое, но ошибка плавающая и в данные момент всё работает. Так что как только так сразу)
