### ISSUE TITLE
Исключение в Wall.GetAsync, если во вложении есть объект типа podcast

### ISSUE THREAD

**Issue by burlakov-nick** [vknet/vk#754]
**Проблема**
Разваливается метод `Wall.GetAsync`, если в посте во вложении есть объект с типом `"type": "podcast"`.

Исключение:
```
Unhandled Exception: VkNet.Exception.InvalidParameterException: The type 'podcast' of attachment is not defined.
   at VkNet.Model.Attachments.Attachment.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.Post.FromJson(VkResponse response)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
   at VkNet.Model.WallGetObject.FromJson(VkResponse response)
   at VkNet.Categories.WallCategory.Get(WallGetParams params, Boolean skipAuthorization)
   at VkNet.Utils.TypeHelper.<>c__DisplayClass1_0`1.<TryInvokeMethodAsync>b__0()
```

В логах клиент пишет:
```
Debug Вызов метода wall.get, с параметрами domain=vandroukiru,offset=1299,count=101,extended=0,v=5.87
Trace Uri = "https://api.vk.com/method/wall.get"
```

Возвращается `response`:
https://gist.github.com/BurlakovNick/69296798b61596b8a073366e00f1a685

Сам пост с вложением-подкастом:
https://gist.github.com/BurlakovNick/f0e056ae33cebcfed336dab7e567436c

**Решение 1**
В класс `Attachment` добавить работу с типом вложения `podcast`

**Решение 2**
Не кидать исключение в методе `Attachment.FromJson`, если встретили незнакомый тип вложения. Это позволит избежать проблем у клиентов VkClient при появлении новых типов вложений. 
https://martinfowler.com/bliki/TolerantReader.html

Похожая проблема не первый раз встречается, судя по всему (https://github.com/vknet/vk/issues/443), хорошо бы раз и навсегда полечить :)

**Comment by inyutin-maxim** [comment]
@BurlakovNick Отличное описание, спасибо за json поможет при написании теста для данного кейса. Полечить раз и навсегда довольно сложно исходя из того что C# строго типизированный язык а вводить dynamic я не хочу, потому при появлении новых объектов будет воспроизводится такая ситуация.

**Comment by CaCTuCaTu4ECKuu** [comment]
Мы же можем создать тип вложение UnknownAttachment с частным сериализатором-десериализатором. Я тоже гляну как нибудь.

**Comment by inyutin-maxim** [comment]
> Мы же можем создать тип вложение UnknownAttachment с частным сериализатором-десериализатором. Я тоже гляну как нибудь.

ну в принципе можно. а пока подкаст скоро подъедет)

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
