### ISSUE TITLE
Ошибка при получении участников группы с использованием фильтра Managers

### ISSUE THREAD

**Issue by domnescu** [vknet/vk#920]
`var users= api.Groups.GetMembers(new GroupsGetMembersParams
                {
                    Filter = GroupsMemberFilters.Managers,
                    GroupId = "187905748", 
                });`
данный код выдаёт ошибку.
Код ошибки: -2147024809
Message: Can not convert Object to Int64.
Источник: Newtonsoft.Json
StackTrace:
```
 at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
at VkNet.Utils.VkResponse.op_Implicit(VkResponse response)
at VkNet.Categories.GroupsCategory.<>c__DisplayClass56_0.<GetMembers>b__0(VkResponse x)
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at VkNet.Utils.VkResponseEx.ToReadOnlyCollection[T](IEnumerable`1 source)
at VkNet.Utils.VkResponseEx.ToReadOnlyCollectionOf[T](IEnumerable`1 responses, Func`2 selector)
at VkNet.Utils.VkResponseEx.ToVkCollectionOf[T](VkResponse response, Func`2 selector, String arrayName)
at VkNet.Categories.GroupsCategory.GetMembers(GroupsGetMembersParams params, Boolean skipAuthorization)
```

Если не использовать фильтр то все работает исправно.

**Comment by domnescu** [comment]
```
{
"response": {
"count": 1,
"items": [{
"id": 235052667,
"role": "creator",
"permissions": ["ads"]
}]
}
}
```

**Comment by inyutin-maxim** [comment]
Добавлено к следующему релизу. Либо можете получить обновление из альфа канала: https://www.myget.org/F/vknet
